---
title: "Homework 5"
author: "Yu-Jen Lin"
output:
  html_document: default
  pdf_document: default
---
#### b04b01036@ntu.edu.tw
#### --------------------------------------------------------------------------------------------------------------------------------------------------------

## 1
```{r}
## barnacles Balanus glandula (Connell 1970)
x = seq(0,9) # age
lx = c(1.0000000, 0.0000620, 0.0000340, 0.0000200, 0.0000155, 0.0000110, 0.0000065, 0.0000020, 0.0000020, 0)
mx = c(0, 4600, 8700, 11600, 12700, 12700, 12700, 12700, 12700, 0)


lx_mx = lx*mx
R0 = sum(lx_mx) # net reproductive rate
x_lx_mx = x*lx*mx # generation time
G = sum(x_lx_mx) / R0
approximate_r = log(R0)/G # approximate r 

r = approximate_r

## lx_mx_e_rx
lx_mx_e_rx = lx_mx*exp(-r*x)


## Lx
Lx = c()
lx[11] = 0 # help me to calculate the last element, will be deleted after calculating Lx
max_i = length(lx)-1
for (i in (1:max_i)) {
 Lx[i] = ( lx[i] + lx[i+1] ) / 2 
}
lx = lx[-11] # return to original lx


## ex 
#### life expectancy
ex = c()
max_i = length(Lx)-1
for (i in (1:max_i)) {
  ex[i] = sum(Lx[i:length(Lx)]) / lx[i]
}


## Vx
#### reproductive value
r = approximate_r
max_i = length(lx)-1
Vx = c()
for (i in 1:max_i){
  Vx[i] = sum(lx_mx_e_rx[i:10])/(exp(-r*(i-1))*lx[i]) 
}


## true_r
r_try = seq(0, 1, by = 0.000001)
d_min = abs(approximate_r-1)
approximation = c()
for (i in r_try){
  equation_result = sum(exp(-i*x)*lx_mx)
  d = abs(equation_result-1) 
  if (d < d_min){
    true_r = i #0.084712
    d_min = d
  }
}



# re-calculating the lx*mx*e-rx and Vx with the true r.

## re-calculate lx_mx_e_rx
r = true_r # true r
lx_mx_e_rx_recal = lx_mx*exp(-r*x)

## calculate Vx
#### reproductive value
r = true_r
max_i = length(lx)-1
Vx_recal = c()
for (i in 1:max_i){
  Vx_recal[i] = sum(lx_mx_e_rx_recal[i:10])/(exp(-r*(i-1))*lx[i]) 
}


result_1 = cbind(x, lx, mx, lx_mx, x_lx_mx, lx_mx_e_rx, Lx, lx_mx_e_rx_recal)
age_range = seq(1,9)
result_2 = cbind(age_range, ex, Vx, Vx_recal)



```

## result_1
```{r}
# install.packages("knitr")
# install.packages("kableExtra")
library(knitr)
library(kableExtra)

kable(result_1) %>%
  kable_styling()


kable(result_2) %>%
  kable_styling()
```
#### --------------------------------------------------------------------------------------------------------------------------------------------------------

## 2
```{r}
m <- c(     0,    0,     0,     0,     0, 322.38,
        0.966,    0,     0,     0,     0,      0,
        0.013, 0.01, 0.125,     0,     0,  3.448,
        0.007,    0, 0.125, 0.238,     0,  30.17,
        0.008,    0,     0, 0.245, 0.167,  0.862,
            0,    0,     0, 0.023,  0.75,      0)

M <- matrix(m,ncol=6, nrow=6, byrow=T)

M_eigen <- eigen(M)
values = M_eigen$values
vector = M_eigen$vectors
values_real = c()
index = c()
for (i in 1:length(values)){
  if (Im(values[i]) == 0){
    j = length(values_real)+1
    values_real[j] = Re(values[i])
    index[j] = i
  }
}

## population growth rate
eigenvalue = max(values_real)
eigenvalue

## stable stage distribution
#### Report the values of the stable stage distribution (re-scale so that the sum = 1).
chosen = index[match(eigenvalue,values_real)]
pre_eigenvector = Re(vector[,chosen])
eigenvector = pre_eigenvector / sum(pre_eigenvector)
eigenvector


## relative reproductive value
#### Report the relative reproductive value for this population, scale the values so that the first element is 1.0.
M2 = t(M)

M_eigen <- eigen(M2)
values = M_eigen$values
vector = M_eigen$vectors
values_real = c()
index = c()
for (i in 1:length(values)){
  if (Im(values[i]) == 0){
    j = length(values_real)+1
    values_real[j] = Re(values[i])
    index[j] = i
  }
}
eigenvalue = max(values_real)
chosen = index[match(eigenvalue,values_real)]
pre_eigenvector = Re(vector[,chosen])
relative_repro = pre_eigenvector / sum(pre_eigenvector[1])
relative_repro

## sensitivity
#### Explore the sensitivity of the population growth rate to changes in this matrix. One by one, increase each non-zero element of the L matrix by 10% (i.e., A[i,j]*1.1). Report the new population growth rate in the following table. Be sure to change the element back before going on to the next element. Describe the two matrix elements (in terms of life histories) that caused the largest increase in population growth rate.
sensitivity = data.frame(matrix(0,dim(M)[1],dim(M)[2]))
for (r in 1:dim(M)[1]){ # rol
  for (c in 1:dim(M)[2]){ # col
    M3 = M
    if (M3[r,c] != 0){
      M3[r,c] = M3[r,c]*1.1
      
      M3_eigen <- eigen(M3)
      values = M3_eigen$values
      values_real = c()
      for (i in 1:length(values)){
        if (Im(values[i]) == 0){
          j = length(values_real)+1
          values_real[j] = Re(values[i])
        }
      }
      ## population growth rate
      sensitivity[r,c] = max(values_real)
    }
  }
}
sensitivity
# sensitivity(6,5) and sensitivity(4,6) cause the largest increase in population growth rate.


```

